### ISSUE TITLE
working fine, but...

### ISSUE THREAD

**Issue by nitad54448** [brianreumere/gandi-automatic-dns#33]
Hi
The script is working fine and I thank you for providing it to the community.
I put it in the cron hourly so far so good.
One addition I see is to make a script to add in cron that calls gad if (and only if) the IP has changed. 
regards

**Comment by brianreumere** [comment]
Hi there. `gad` basically already does that. If it determines that your IP address has not changed, it exits and doesn't do anything else. It *does* have to make a request to the Gandi API to determine if your current IP address matches what is in your DNS zone file.

There was a pull request a while ago to add a feature where it would cache the current IP address in a file, but I never merged the feature because I didn't see the benefit of it (the Gandi API allows quite a high request rate, and you could theoretically run `gad` once per minute and not get rate limited).

Are you wanting to run `gad` more often than hourly? Or what is your use case? I'd be willing to re-visit the option to cache the current/last known IP address so that you can get more "realtime" updates to DNS when your IP address changes.

**Comment by nitad54448** [comment]
Hi
I assumed that Gad will "write" the A or AAAA record every time the cron job is launched. But I understand now, you are right, it is best to check directly if the current IP matches that on the record.
Thanks again for your script, it is very useful, my IP changes once a month or so and I am not running any critical services, so one hour seems ok.
Regards

**Comment by nitad54448** [comment]
Hi
Sorry to bother you again. It is possible that I use a wildcard in the name record, such as
*.lan
(I have a record like this with Gandi)
Thanks

**Comment by brianreumere** [comment]
Yes, you should be able to update a wildcard record. You may need to enclose the record names in single quotes, like `-r '*'` or `-r '*.lan'`.
