### ISSUE TITLE
Update A and AAAA simultaneously

### ISSUE THREAD

**Issue by Alexandero89** [brianreumere/gandi-automatic-dns#34]
Hey,
thanks for your work!

But is there a special reason the script is not updating the A and the AAAA record simultaneously?
As i see it i have to start the script twice. Once for the A record and then with the "-6" argument for the AAAA record.

Would it not make sense to update both by default and make ipv6 opt-out via cli argument?

**Comment by brianreumere** [comment]
The script didn't originally support IPv6/AAAA records, and it was [simplest at the time](https://github.com/brianreumere/gandi-automatic-dns/commit/4dd3d534316d68568ab02c4a0ec7cbf3a0acae9f) to add that functionality as a separate flag.

It would require somewhat significant re-working of the script to update both A and AAAA records with a single command, so for now it will be left as-is. I also don't want to change the default behavior of the script without significant reason to do so. Running the script twice really only adds a single API call (to get the active version of the zonefile), so that's the recommended way to update both A and AAAA records.
